from operators.fetch_weather_operator import BaseFetchWeatherOperator, FetchPrecipitationOperator, FetchAirQualityOperatorV2
from operators.mongo_record_weather_data_operator import MongoRecordWeatherDataOperator
from operators.custom_email_operator import CustomEmailOperator
from operators.create_plot_operator import CreatePlotOperator
from operators.postgres_record_weather_data_operator import PostgresRecordWeatherDataOperator