from operators.fetch_weather_operator import BaseFetchWeatherOperator, FetchPrecipitationOperator, FetchAirQualityOperator
from operators.mongo_record_weather_data_operator import MongoRecordWeatherDataOperator
from operators.custom_email_operator import CustomEmailOperator