#Percipitation Constants
APPARENT_TEMPERATURE = 'apparent_temperature'
TEMPERATURE = 'temperature_2m'
WIND_SPEED = 'wind_speed_10m'
HUMIDITY = 'relative_humidity_2m'
PRECIPITATION = 'precipitation'
CLOUD_COVER = 'cloudcover'
VISIBILITY = 'visibility'
UV_INDEX = 'uv_index'
PM_10 = 'pm10'
PM_2_5 = 'pm2_5'
LATITUDE = 'latitude'
LONGITUDE = 'longitude'
HOURLY_DATA = 'hourly'
TIMEZONE = 'timezone'
AUTO_TIMEZONE = 'auto'
FORECAST_DAYS = 'forecast_days'
