#Percipitation Constants
APPARENT_TEMPERATURE = 'apparent_temperature'
PRECIPITATION = 'precipitation'
CLOUD_COVER = 'cloudcover'
VISIBILITY = 'visibility'
LATITUDE = 'latitude'
LONGITUDE = 'longitude'
HOURLY_DATA = 'hourly'
TIMEZONE = 'timezone'
AUTO_TIMEZONE = 'auto'
FORECAST_DAYS = 'forecast_days'

#AirQuality Constants
COUNTRY = 'country'
STATE = 'state'
CITY = 'city'
API_KEY = 'key'
AIR_API_KEY = 'AIR_API'
RESPONSE_DATA = 'data'
CURRENT_DATA = 'current'
WEATHER = 'weather'
POLLUTION = 'pollution'
TIMESTAMP = 'timestamp'
ABBREVIATED_TIMESTAMP = 'ts'
AIR_QUALITY = 'air_quality'
ABBREVIATED_AIR_QUALITY = 'aqius'
TEMPERATURE = 'temperature'
ABBREVIATED_TEMPERATURE = 'tp'
HUMIDITY = 'humidity'
ABBREVIATED_HUMIDITY = 'hu'
WIND_SPEED = 'wind_speed'
ABBREVIATED_WIND_SPEED = 'ws'
